"use client";

import dynamic from "next/dynamic";import Link from "next/link";import {acharya} from "@/src/data/acharya";import {kathas} from "@/src/data/kathas";import {events} from "@/src/data/events";
const Cosmos=dynamic(()=>import("@/components/three/VedicCosmos"),{ssr:false});
export default function Home(){return <><main><section className="hero"><div className="canvas"><Cosmos/></div><div className="veil"/><div className="heroText"><div className="eyebrow">Divya Akash • Sacred storytelling × celestial mathematics</div><h1 className="hindi">{acharya.nameHindi}</h1><p className="sub">कथा, ज्योतिष और सनातन ज्ञान के लिए एक शांत, आधुनिक डिजिटल स्थान। सत्यापित सार्वजनिक जानकारी उपलब्ध होते ही यह अनुभव वास्तविक जीवन-यात्रा, आयोजन और मीडिया से समृद्ध होगा।</p><div className="actions"><Link className="btn primary" href="/book">कथा हेतु संपर्क करें</Link><Link className="btn" href="/jyotish">ज्योतिष परामर्श</Link><a className="btn" href={acharya.facebook} target="_blank">Facebook</a></div></div></section>
<section className="section"><div className="shell"><div className="eyebrow">परिचय</div><h2>परंपरा की गरिमा,<br/>डिजिटल युग की सहजता।</h2><p className="muted">इस वेबसाइट की सामग्री source-first है: पेशेवर उपाधि, जीवनी, सेवाएँ, आयोजन, संपर्क और मीडिया केवल प्राथमिक Facebook स्रोत से सत्यापन के बाद प्रकाशित किए जाते हैं।</p></div></section>
<section className="section"><div className="shell"><div className="eyebrow">कथा</div><h2>कथा केवल श्रवण नहीं —<br/>ईश्वर से संवाद है।</h2>{kathas.length?<div className="grid">{kathas.map(k=><div className="card" key={k.slug}><b>{k.hindi}</b><p>{k.description}</p></div>)}</div>:<div className="empty">सत्यापित कथा श्रेणियाँ प्राथमिक स्रोत समीक्षा के बाद यहाँ दिखाई जाएँगी।</div>}</div></section>
<section className="section"><div className="shell"><div className="eyebrow">ज्योतिष</div><h2>ज्योतिष — समय को समझने की वैदिक दृष्टि</h2><p className="muted">परामर्श श्रेणियाँ तभी दिखाई जाती हैं जब वे सत्यापित सार्वजनिक पेशेवर सामग्री में स्पष्ट रूप से उपलब्ध हों। कोई चमत्कारी या गारंटीड दावा नहीं।</p><Link className="btn" href="/jyotish">ज्योतिष अनुभाग देखें</Link></div></section>
<section className="section"><div className="shell"><div className="eyebrow">आयोजन</div><h2>आगामी कथा एवं आयोजन</h2>{events.length?<div className="grid">{events.map(e=><div className="card" key={e.slug}><b>{e.title}</b><p>{e.date} · {e.city}</p></div>)}</div>:<div className="empty">आगामी कथा एवं कार्यक्रम की जानकारी शीघ्र साझा की जाएगी।</div>}</div></section></main></>}
